[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "marketanalyzerx"
version = "0.1.0"
description = "A stock market analysis application" 